[package]
name = "ringhopper"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
ringhopper-structs = { path = "../ringhopper-structs", default-features = false }
minxp = { version = "0.1.6", optional = true }

[features]
std = ["ringhopper-structs/std"]
minxp = ["dep:minxp"]
default = ["std"]

[lints]
workspace = true
