[package]
name = "ringhopper-structs"
version = "0.2.0"
license = "GPL-3.0-only"
edition = "2024"

[dependencies]
funnel-web = { git = "https://github.com/FishAndRips/funnel-web.git", rev = "4cae0316fb98a58fa93f67984b609fbd919fb8fb" }
ringhopper-structs-codegen = { path = "../ringhopper-structs-codegen" }
byteorder = "1.5.0"

[features]
default = []
std = []
