[package]
name = "ringhopper-structs"
version = "0.2.0"
license = "GPL-3.0-only"
edition = "2024"

[dependencies]
funnel-web = { git = "https://github.com/FishAndRips/funnel-web.git", rev = "d52fa441e6c06c1fea04e4e9cefd980ebea69063" }
ringhopper-structs-codegen = { path = "../ringhopper-structs-codegen" }
byteorder = "1.5.0"

[features]
default = []
std = []
