[package]
name = "ringhopper-structs-codegen"
version = "0.2.0"
license = "GPL-3.0-only"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
ringhopper-definitions = { git = "https://github.com/FishAndRips/ringhopper-definitions.git", rev = "e25a1cfc697d75258b29f123da3677d0c4c41d6a" }

[lints]
workspace = true
