[package]
name = "ringhopper-structs-codegen"
version = "0.2.0"
license = "GPL-3.0-only"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
ringhopper-definitions = { git = "https://github.com/FishAndRips/ringhopper-definitions.git", rev = "819e620f20b4ade2ea04b95d52b7a700aef9d93b" }

[lints]
workspace = true
